FROM openjdk:17

ARG JAR_FILE=/build/libs/smupool.jar

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD

ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]